### ISSUE TITLE
安装完毕运行后，刷图可以使用，但创作不能

### ISSUE THREAD

**Issue by senran9999** [newlxj/sdweb-multi-user-website#12]
安装完毕运行后，刷图可以使用，但创作不能，显示如图
![截屏2024-01-25 13 41 06](https://github.com/newlxj/stablediffusion-website-online/assets/70112836/1c2108b8-b5f3-4d05-a062-98e49c0fb81b)

**Comment by newlxj** [comment]
检查一下日志，看看是不是版本差异造成的，这个在1.5下测试没问题
