### ISSUE TITLE
Add English Translation for Documentation for internasional viewer

### ISSUE THREAD

**Issue by tukangcode** [newlxj/sdweb-multi-user-website#2]
Hi i find this work interesting, i using translator so it not bother me much but you need to Translate Readme.md aka documentation to English so everyone can help you develop it, it also make people easy to find your project and discuss it compare letting this untranslated. This project have huge potential but if left untranslated to english it will not progress or develop.

**Comment by newlxj** [comment]
Thank you. This is a great proposal. As I don't have much time for detailed translation work, I can only provide it in Chinese at present. However, you can use Chrome's translation function for translation. Thank you for your suggestion

**Comment by newlxj** [comment]
https://github.com/newlxj/sdweb-multi-user-website/blob/main/README_EN.md

**Comment by tukangcode** [comment]
Thanks, i hope your project success and get lot star.
