### ISSUE TITLE
Support for ControlNet?

### ISSUE THREAD

**Issue by kae1616** [newlxj/sdweb-multi-user-website#6]
Any possibility to integrate ControlNet into this UI? 有想过要加Control net吗？

**Comment by newlxj** [comment]
ControlNet其实好加，不过最近没时间，如果你需要加我可以告诉你思路。并且欢迎贡献。

**Comment by kae1616** [comment]
行哦 什么联系方式呢？

**Comment by newlxj** [comment]
你可以添加QQ群来讨论  793072950
