### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by altasni** [newlxj/sdweb-multi-user-website#8]
ImportError: cannot import name 'url_quote' from 'werkzeug.urls'
按照步骤安装，启动就报错，请问这个怎么解决，python版本是3.10，typing_extensions 4.8.0

**Comment by altasni** [comment]
其实是sqlalchemy-2.0.0的报错，换成sqlalchemy-1.4的就没问题，但是后面的sql有不兼容的了

**Comment by altasni** [comment]
请问这个应该怎么解决？

**Comment by newlxj** [comment]
> 按照步骤安装，启动就报错，请问这个怎么解决，python版本是3.10，typing_extensions 4.8.0

你单独按照安装脚本里面执行试试
